-define(TraceCall(TS, From, Where, Req), {TS, call, {From, Where, Req}}).
-define(TraceNewProcess(TS, Proc, AbsId, Creator, EntryInfo), {TS, new_process, {Proc, AbsId, Creator, EntryInfo}}).
-define(TraceSchedule(TS, Where, Proc, Info), {TS, schedule, Where, Proc, Info}).
-define(TraceSend(TS, Where, From, To, Type, Content, Effect), {TS, send, {Where, From, To, Type, Content, Effect}}).
-define(TraceRecv(TS, Where, To, Type, Content), {TS, recv, {Where, To, Type, Content}}).
-define(TraceRead(TS, Var), {TS, read, {Var}}).
-define(TraceWrite(TS, Var), {TS, write, {Var}}).
-define(TraceBarrier(TS), {TS, barrier}).
-define(TraceReportState(TS, TraceInfo, State), {TS, report_state, TraceInfo, State}).
